### PR TITLE
expose shoot api server

### PR DESCRIPTION
**Pull request by mfranczy**
Signed-off-by: Marcin Franczyk <marcin0franczyk@gmail.com>

**How to categorize this PR?**

/area control-plane
/kind enhancement
/priority normal
/platform kubevirt

**What this PR does / why we need it**:
Expose shoot apiserver
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Expose shoot apiserver
```

### CODE REVIEW

**Review by stoyanr — CHANGES_REQUESTED** [review]
Thanks for the PR! Looks quite good, except that the `etcdStorage` field in the ensurer looks redundant and is not currently used. Could you please remove it?
Also, no need for the long logger name, it's appended to `kubevirt-controlplaneexposure-webhook`, so you could shorten that to `ensurer`.
These are things I think we missed in the previous PR, let's fix them now.

**Comment by stoyanr** [comment]
The `verify` check is currently failing with:
```
Downloading https://kubernetes-helm.storage.googleapis.com/helm-og:image-linux-amd64.tar.gz
SHA sum of /tmp/helm-installer-uJfT3i/helm-og:image-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm with the arguments provided: --version v2.13.1
```
To get rid of this error, you could either:
* Revendor to a newer Gardener, see e.g. https://github.com/gardener/gardener-extension-provider-azure
* Copy the fixed `install-requirements.sh` script from the newer Gardener to your `hack` folder and call it directly.
I guess the second option is easier for now, this could be done in a separate PR.

**Review by stoyanr — APPROVED** [review]

**Comment by mfranczy** [comment]
@stoyanr as we discussed let's leave the etcd field in control plane exposure as @rootfs will work with it

**Pull request merged**
